/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FarmItem: typeof import('./src/components/FarmItem.vue')['default']
    FarmsList: typeof import('./src/components/FarmsList.vue')['default']
    GameHeader: typeof import('./src/components/GameHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TickProgressBar: typeof import('./src/components/TickProgressBar.vue')['default']
  }
}
